name: MDC AWS Org Onboarding


on:
workflow_dispatch:
inputs:
org:
description: "Organization tfvars file name (ex: test-org or prod-org)"
required: true
default: "test-org"


permissions:
id-token: write
contents: read


jobs:
deploy:
runs-on: ubuntu-latest


env:
AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
AZURE_RG: ${{ secrets.AZURE_RESOURCE_GROUP }}


steps:
- name: Checkout
uses: actions/checkout@v4


- name: Azure login
uses: azure/login@v1
with:
client-id: ${{ secrets.AZURE_CLIENT_ID }}
tenant-id: ${{ secrets.AZURE_TENANT_ID }}
client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}


- name: Configure AWS credentials (OIDC)
uses: aws-actions/configure-aws-credentials@v4
with:
role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
aws-region: ${{ secrets.AWS_REGION }}


- name: Setup Terraform
uses: hashicorp/setup-terraform@v3
with:
terraform_version: 1.6.6


- name: Terraform Init
working-directory: ./terraform
run: terraform init


- name: Terraform Apply for selected org
working-directory: ./terraform
run: terraform apply -auto-approve -var-file="orgs/${{ github.event.inputs.org }}.tfvars"
