name: MDC AWS Org Onboarding

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  id-token: write     # Needed for AWS OIDC auth
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Authenticate to Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          # FIX: Replaced individual credentials (client-id, tenant-id, secret) 
          # with the single 'creds' input, which takes a JSON Service Principal object.
          # This resolves the 'Unexpected input' warning from the runtime.
          creds: ${{ toJSON({
            clientId: secrets.AZURE_CLIENT_ID,
            clientSecret: secrets.AZURE_CLIENT_SECRET,
            tenantId: secrets.AZURE_TENANT_ID,
            subscriptionId: env.AZURE_SUBSCRIPTION_ID
          }) }}

      # Fetch MDC CloudFormation StackSet template URL
      - name: Fetch MDC CloudFormation Template URL
        id: fetch_template
        run: |
          TEMPLATE_URL=$(az rest --method post \
            --url "https://management.azure.com/subscriptions/${AZURE_SUBSCRIPTION_ID}/providers/Microsoft.Security/defenderForCloudAwsOffering/organizationCloudFormationTemplate?api-version=2023-10-01-preview" \
            --query 'templateUrl' -o tsv)
          echo "template_url=$TEMPLATE_URL" >> $GITHUB_OUTPUT

      # Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -var="template_url=${{ steps.fetch_template.outputs.template_url }}"

      # OPTIONAL — Create MDC connector in Azure
      - name: Create MDC Connector (Azure)
        run: |
          # NOTE: Replace 'MDC-Connectors-RG' with the actual Resource Group name where the connector should reside.
          az rest --method put \
            --url "https://management.azure.com/subscriptions/${AZURE_SUBSCRIPTION_ID}/resourceGroups/MDC-Connectors-RG/providers/Microsoft.Security/multiCloudConnectors/awsOrgConnector?api-version=2023-10-01-preview" \
            --body '{
              "location": "centralus",
              "properties": {
                "cloudName": "AWS",
                "environmentType": "awsOrganization",
                "hierarchyIdentifier": "o-a1b2c3d4e5", # <-- REPLACE with your AWS Organization ID (e.g., 'o-xxxxxxxxxx')
                "authenticationDetails": {
                  "authenticationType": "awsAssumeRole",
                  "roleArn": "arn:aws:iam::123456789012:role/DefenderForCloud-Connector-Role" # <-- REPLACE with your AWS Management Account ID
                }
              }
            }'
