name: MDC AWS Org Onboarding

on:
  workflow_dispatch:
    inputs:
      org:
        description: "Organization tfvars file (ex: test-org or prod-org)"
        required: true
        default: "test-org"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_SUBSCRIPTION_ID: "c5fddee6-8712-4dd8-b580-637b37dc5472"
      AZURE_RG: "kpmg-testing"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: "89c087b6-1a3d-4153-b9c5-cc0e20af8d30"
          tenant-id: "831de134-d871-4cd7-823a-eacb69c699c8"
          client-secret: "kaA8Q~w5cPFB82eZxcF9srMSeVnOF0ZWoSQIwa4M"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::746669220365:role/oidc-terraform-role"
          aws-region: "eu-west-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply for selected org
        working-directory: ./terraform
        run: terraform apply -auto-approve -var-file="orgs/${{ github.event.inputs.org }}.tfvars"
